name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Publish package
        run: |
          cp .config/__LICENCE__ .
          sed -i "`sed -n '/<\/properties>/=' pom.xml`r .config/setting.xml" pom.xml
          mvn clean archetype:create-from-project
          sed -i "`sed -n '/<name>.*<\/name>/=' target/generated-sources/archetype/pom.xml | head -1`r .config/setting.xml"  target/generated-sources/archetype/pom.xml
          cd target/generated-sources/archetype
          mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}